
namespace Sharkable;

/// <summary>
/// Minimal API endpoint. Implement <see cref="AddRoutes"/> to define routes,
/// or leave empty when using AutoCrud (<see cref="IAutoCrudEntity{T}"/>).
/// The class name (minus "Endpoint"/"Service" suffix) becomes the URL group prefix.
/// </summary>
public interface ISharkEndpoint
{
    /// <summary>
    /// Define routes by calling <c>app.MapGet()</c>, <c>app.MapPost()</c>, etc.
    /// Routes are automatically grouped under <c>api/{group-name}</c>.
    /// Default is a no-op — leave empty when all routes are generated by AutoCrud.
    /// </summary>
    void AddRoutes(IEndpointRouteBuilder app) { }
}