using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Sharkable.Analyzers;

/// <summary>
/// Source Generator that discovers all <see cref="IAutoCrudEntity{T}"/>
/// implementations at compile time and emits a preservation class that
/// forces the .NET Native AOT trimmer to keep entity types. This
/// eliminates the need for manual <c>rd.xml</c> configuration.
/// </summary>
[Generator]
public sealed class AutoCrudAotPreserver : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entityTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (n, _) => n is ClassDeclarationSyntax c
                    && c.BaseList?.Types.Any(t => t.Type.ToString().StartsWith("IAutoCrudEntity")) == true,
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl);
                    if (symbol == null) return null;

                    foreach (var iface in symbol.AllInterfaces)
                    {
                        if (iface.Name == "IAutoCrudEntity" && iface is INamedTypeSymbol { IsGenericType: true, TypeArguments.Length: 1 } namedIface)
                        {
                            var entityType = namedIface.TypeArguments[0];
                            return entityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        }
                    }
                    return null;
                })
            .Where(t => t != null)
            .Collect();

        context.RegisterSourceOutput(entityTypes, (ctx, types) =>
        {
            var distinctTypes = types.Distinct().ToList();
            if (distinctTypes.Count == 0) return;

            var source = $@"
// <auto-generated/>
namespace Sharkable.AutoCrud.Aot;

[System.Runtime.CompilerServices.CompilerGenerated]
internal static class AutoCrudAotPreservation
{{
    /// <summary>
    /// Forces the .NET Native AOT trimmer to preserve all entity types
    /// referenced by <see cref=""IAutoCrudEntity{{T}}""/> implementations.
    /// Generated automatically — no rd.xml needed.
    /// </summary>
    internal static readonly System.Type[] _preservedTypes = new System.Type[]
    {{
{string.Join(",\n", distinctTypes.Select(t => $"        typeof({t})"))}
    }};
}}
";
            ctx.AddSource("AutoCrudAotPreservation.g.cs", source);
        });
    }
}
