using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Sharkable.Analyzers;

/// <summary>
/// Source Generator that scans all return types from endpoint delegates
/// and emits <c>typeof(UnifiedResult&lt;T&gt;)</c> references to keep
/// them alive under Native AOT trimming. Complements <see cref="AutoCrudAotPreserver"/>.
/// </summary>
[Generator]
public sealed class UnifiedResultAotPreserver : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var returnTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (n, _) => n is InvocationExpressionSyntax inv
                    && IsEndpointMethod(inv),
                transform: static (ctx, _) =>
                {
                    var inv = (InvocationExpressionSyntax)ctx.Node;
                    var lambda = inv.ArgumentList.Arguments
                        .OfType<ArgumentSyntax>()
                        .SkipWhile(a => a.Expression is LiteralExpressionSyntax) // skip route string
                        .Select(a => a.Expression)
                        .OfType<LambdaExpressionSyntax>()
                        .FirstOrDefault();

                    if (lambda == null) return null;

                    var returnInfo = ctx.SemanticModel.GetSymbolInfo(
                        lambda is ParenthesizedLambdaExpressionSyntax p
                            ? GetReturnExpression(p)
                            : GetReturnExpression((SimpleLambdaExpressionSyntax)lambda));

                    if (returnInfo.Symbol is INamedTypeSymbol namedReturnType)
                    {
                        // Handle Task<T>, ValueTask<T>, IResult, etc.
                        var innerType = UnwrapAsyncReturnType(namedReturnType);
                        if (innerType != null)
                            return innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    }

                    return null;
                })
            .Where(t => t != null)
            .Collect();

        context.RegisterSourceOutput(returnTypes, (ctx, types) =>
        {
            var distinct = types.Distinct().ToList();
            if (distinct.Count == 0) return;

            var source = $@"
// <auto-generated/>
namespace Sharkable.UnifiedResult.Aot;

[System.Runtime.CompilerServices.CompilerGenerated]
internal static class UnifiedResultAotPreservation
{{
    internal static readonly System.Type[] s_types = new System.Type[]
    {{
{string.Join(",\n", distinct.Select(t => $"        typeof(global::Sharkable.UnifiedResult<{t}>)"))}
    }};
}}
";
            ctx.AddSource("UnifiedResultAotPreservation.g.cs", source);
        });
    }

    private static bool IsEndpointMethod(InvocationExpressionSyntax inv)
    {
        if (inv.Expression is MemberAccessExpressionSyntax ma)
        {
            var name = ma.Name.Identifier.Text;
            return name is "MapGet" or "MapPost" or "MapPut" or "MapPatch" or "MapDelete";
        }
        return false;
    }

    private static ExpressionSyntax? GetReturnExpression(ParenthesizedLambdaExpressionSyntax lambda)
    {
        if (lambda.Body is BlockSyntax block && block.Statements.Count > 0)
        {
            var last = block.Statements.LastOrDefault();
            if (last is ReturnStatementSyntax ret)
                return ret.Expression;
            if (last is ExpressionStatementSyntax expr)
                return expr.Expression;
        }
        return lambda.Body as ExpressionSyntax;
    }

    private static ExpressionSyntax? GetReturnExpression(SimpleLambdaExpressionSyntax lambda)
    {
        if (lambda.Body is BlockSyntax block && block.Statements.Count > 0)
        {
            var last = block.Statements.LastOrDefault();
            if (last is ReturnStatementSyntax ret)
                return ret.Expression;
            if (last is ExpressionStatementSyntax expr)
                return expr.Expression;
        }
        return lambda.Body as ExpressionSyntax;
    }

    private static INamedTypeSymbol? UnwrapAsyncReturnType(INamedTypeSymbol type)
    {
        var target = type;
        // Unwrap Task<T>, ValueTask<T>
        while (target is { IsGenericType: true, TypeArguments.Length: 1 })
        {
            var name = target.ConstructedFrom.Name;
            if (name is "Task" or "ValueTask")
            {
                target = target.TypeArguments[0] as INamedTypeSymbol;
                if (target == null) break;
            }
            else
            {
                break;
            }
        }
        return target;
    }
}
