@Sharkable.Sample_HostAddress = http://localhost:5173

GET {{Sharkable.Sample_HostAddress}}/todos/
Accept: application/json

###

GET {{Sharkable.Sample_HostAddress}}/todos/1
Accept: application/json

###
